logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

# Entrypoints, http and https
[entryPoints]
  # http should be redirected to https
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  # https is the default
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
# Email address used for registration
email = "sarit@elcolie.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true
  # Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
  [acme.httpChallenge]
  entryPoint = "http"

[file]
[backends]
  [backends.rasa]
    [backends.rasa.servers.server1]
      url = "http://rasa:5005"

[frontends]
  [frontends.rasa]
    backend = "rasa"
    passHostHeader = true
    [frontends.rasa.headers]
      HostsProxyHeaders = ['X-CSRFToken']
    [frontends.rasa.routes.dr1]
      rule = "Host:gleng.elcolie.com"
